rm(list=ls())

library(tidyverse)
library(tictoc)
library(raster)


# load the predicted map of interpolation percentage of environmental PCs
Global_PCA_IntExt <- raster("**/Global_Analysis/Model_Output/BI_PCA_pct_int_ext_FSD.tif")

###---Map generated by spatial-clustering random forest----
# load the predicted map
BI_bestRfModel_SpatialClustering <- raster("**/Source_Data/SourceData_Fig4B.tif")
# check the map
plot(BI_bestRfModel_SpatialClustering)

## The final Figure 4A is made in QGIS using this masked map product


###---Map generated by environmental-clustering random forest----
# load the predicted map
BI_bestRfModel_EnvClustering <- raster("**/Global_Analysis/Model_Output/BI_PredictedEnsembleMean_PCA_Kmeans_FSD.tif")
# check the map
plot(BI_bestRfModel_EnvClustering)

# we only retain pixels in which environmental conditions 
# are well represented by our training data (> 90% interpolation)
# by setting the extrapolated regions as NA
BI_bestRfModel_EnvClustering_90interpolation <- BI_bestRfModel_EnvClustering[Global_PCA_IntExt<0.9] <- NA
## The final Figure 4B is made in QGIS using this masked map product

###---Histograms to show differences among three types of clusters----

## load plot-level aggregated forest data
# GFBI_Df2_Aggregated_Full_2 <- readRDS("**/Global_Analysis/Data/GFBI_Df2_aggregated_New.rds")
GFBI_Df2_Aggregated_Full_2 <- read.csv("**/Source_Data/SourceData_Fig1D-F.csv")

# we accounted for the potential impact of human management on the 
# establishment of monocultures by only keeping plots 
# 1) with at least ten trees, 
# 2) with at least two species, 
# 3) in which the relative basal area of the tree species with the largest cumulative basal area in the plot was smaller than 75%
GFBI_Df2_Aggregated_Full_2_filtered <- GFBI_Df2_Aggregated_Full_2[GFBI_Df2_Aggregated_Full_2$spp_maxprop<=0.75 & GFBI_Df2_Aggregated_Full_2$count>=10 & GFBI_Df2_Aggregated_Full_2$spp.count>=2,]

## load cluster-level aggregated forest data
GFBI_Df3_Scaled_10min_Full <-readRDS("**/Global_Analysis/Data/GFBI_Df3_Scaled_10min_FullStandardized.rds")

# retain cluster with sample size >= 50, to make sure BI can accurately depict the distribution
GFBI_Df3_Scaled_10min <- GFBI_Df3_Scaled_10min_Full[GFBI_Df3_Scaled_10min_Full$SampleSize>=50, ]%>%drop_na()
# index of bimodal clusters
Bimodal_Cluster_index <- GFBI_Df3_Scaled_10min$Cluster_10min[GFBI_Df3_Scaled_10min$BI<0.22 & GFBI_Df3_Scaled_10min$BI> -0.22] # take strictly bimodal grids
# index of evergreen-dominated clusters
EV_Cluster_index <- GFBI_Df3_Scaled_10min$Cluster_10min[GFBI_Df3_Scaled_10min$BI>0.22]
# index of deciduous-dominated clusters
DE_Cluster_index <- GFBI_Df3_Scaled_10min$Cluster_10min[GFBI_Df3_Scaled_10min$BI< -0.22]

# forest plot data within bimodal clusters
GFBI_Df2_Bimodal_0 <- GFBI_Df2_Aggregated_Full_2_filtered[GFBI_Df2_Aggregated_Full_2_filtered$Cluster_10min%in%Bimodal_Cluster_index,]%>%drop_na()
# forest plot data within evergreen-dominated clusters
GFBI_Df2_EV_0 <- GFBI_Df2_Aggregated_Full_2_filtered[GFBI_Df2_Aggregated_Full_2_filtered$Cluster_10min%in%EV_Cluster_index,]%>%drop_na()
# forest plot data within deciduous-dominated clusters
GFBI_Df2_DE_0 <- GFBI_Df2_Aggregated_Full_2_filtered[GFBI_Df2_Aggregated_Full_2_filtered$Cluster_10min%in%DE_Cluster_index,]%>%drop_na()

# match the cluster index of plot-level dataset to the cluster-level dataset
BI_index <- GFBI_Df2_Aggregated_Full_2_filtered$Cluster_10min%in%Bimodal_Cluster_index
EV_index <- GFBI_Df2_Aggregated_Full_2_filtered$Cluster_10min%in%EV_Cluster_index
DE_index <- GFBI_Df2_Aggregated_Full_2_filtered$Cluster_10min%in%DE_Cluster_index

####---check the distribution of plot-level relEV in deciduous-dominated clusters
aL_De<-ggplot(GFBI_Df2_Aggregated_Full_2_filtered_stratSample[DE_index,],aes(x=EV_Density/(DE_Density+EV_Density),fill=..x..))+geom_histogram(binwidth = binwidthx)+xlab("relEV")+theme_classic()+
  scale_fill_gradient(low='red', high='blue')+ggtitle(paste0("model"))+ theme(legend.title = element_blank())
aDest_De<-ggplot_build(aL_De)$data[[1]]
ASest_De<-data.frame(x=aDest_De$x,count=aDest_De$count,relf=aDest_De$count/sum(aDest_De$count),id=i)

# Figure 4C left
ggplot()+geom_bar(data=ASest_De,aes(x=x,y=relf),fill="red",show.legend = FALSE,stat="identity",alpha=0.5)+
  theme_classic()+
  ylab("Relative Frequency")+xlab("Relative Abundance Evergreen Trees")+
  theme(axis.text.x=element_text(size=12, face="bold"),
        axis.text.y=element_text(size=12, face="bold"),
        axis.title.x=element_text(size=16,face="bold"),
        axis.title.y=element_text(size=16,face="bold"),
        legend.text = element_text(colour = "black", size = 10, face = "bold"),
        legend.title = element_text(colour = "black", size = 12, face = "bold"))


####---check the distribution of plot-level relEV in bimodal clusters
aL_Bi<-ggplot(GFBI_Df2_Aggregated_Full_2_filtered[BI_index,],aes(x=relEV)))+geom_histogram(binwidth = binwidthx)+xlab("relEV")+theme_classic()+
  theme(legend.title = element_blank())
aDest_Bi<-ggplot_build(aL_Bi)$data[[1]]
ASest_Bi<-data.frame(x=aDest_Bi$x,count=aDest_Bi$count,relf=aDest_Bi$count/sum(aDest_Bi$count),id=i)

# Figure 4C middle
ggplot()+geom_bar(data=ASest_Bi,aes(x=x,y=relf),fill="darkcyan",show.legend = FALSE,stat="identity",alpha=0.5)+
  theme_classic()+
  ylab("Relative Frequency")+xlab("Relative Abundance Evergreen Trees")+
  theme(axis.text.x=element_text(size=12, face="bold"),
        axis.text.y=element_text(size=12, face="bold"),
        axis.title.x=element_text(size=16,face="bold"),
        axis.title.y=element_text(size=16,face="bold"),
        legend.text = element_text(colour = "black", size = 10, face = "bold"),
        legend.title = element_text(colour = "black", size = 12, face = "bold"))

####---check the distribution of plot-level relEV in evergreen-dominated clusters
aL_Ev<-ggplot(GFBI_Df2_Aggregated_Full_2_filtered[EV_index,],aes(x=relEV)))+geom_histogram(binwidth = binwidthx)+xlab("relEV")+theme_classic()+
  theme(legend.title = element_blank())
aDest_Ev<-ggplot_build(aL_Ev)$data[[1]]
ASest_Ev<-data.frame(x=aDest_Ev$x,count=aDest_Ev$count,relf=aDest_Ev$count/sum(aDest_Ev$count),id=i)

# Figure 4C right
ggplot()+geom_bar(data=ASest_Ev,aes(x=x,y=relf),fill="blue",show.legend = FALSE,stat="identity",alpha=0.5)+
  theme_classic()+
  ylab("Relative Frequency")+xlab("Relative Abundance Evergreen Trees")+
  theme(axis.text.x=element_text(size=12, face="bold"),
        axis.text.y=element_text(size=12, face="bold"),
        axis.title.x=element_text(size=16,face="bold"),
        axis.title.y=element_text(size=16,face="bold"),
        legend.text = element_text(colour = "black", size = 10, face = "bold"),
        legend.title = element_text(colour = "black", size = 12, face = "bold"))
